// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: newpaid/newpaid.proto

package newpaid

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddMoneyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GrpcToken     string                 `protobuf:"bytes,1,opt,name=grpc_token,json=grpcToken,proto3" json:"grpc_token,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount        int64                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddMoneyRequest) Reset() {
	*x = AddMoneyRequest{}
	mi := &file_newpaid_newpaid_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddMoneyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMoneyRequest) ProtoMessage() {}

func (x *AddMoneyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_newpaid_newpaid_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMoneyRequest.ProtoReflect.Descriptor instead.
func (*AddMoneyRequest) Descriptor() ([]byte, []int) {
	return file_newpaid_newpaid_proto_rawDescGZIP(), []int{0}
}

func (x *AddMoneyRequest) GetGrpcToken() string {
	if x != nil {
		return x.GrpcToken
	}
	return ""
}

func (x *AddMoneyRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AddMoneyRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type AddMoneyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddMoneyResponse) Reset() {
	*x = AddMoneyResponse{}
	mi := &file_newpaid_newpaid_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddMoneyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMoneyResponse) ProtoMessage() {}

func (x *AddMoneyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_newpaid_newpaid_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMoneyResponse.ProtoReflect.Descriptor instead.
func (*AddMoneyResponse) Descriptor() ([]byte, []int) {
	return file_newpaid_newpaid_proto_rawDescGZIP(), []int{1}
}

func (x *AddMoneyResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AddMoneyResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetMoneyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GrpcToken     string                 `protobuf:"bytes,1,opt,name=grpc_token,json=grpcToken,proto3" json:"grpc_token,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMoneyRequest) Reset() {
	*x = GetMoneyRequest{}
	mi := &file_newpaid_newpaid_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMoneyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMoneyRequest) ProtoMessage() {}

func (x *GetMoneyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_newpaid_newpaid_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMoneyRequest.ProtoReflect.Descriptor instead.
func (*GetMoneyRequest) Descriptor() ([]byte, []int) {
	return file_newpaid_newpaid_proto_rawDescGZIP(), []int{2}
}

func (x *GetMoneyRequest) GetGrpcToken() string {
	if x != nil {
		return x.GrpcToken
	}
	return ""
}

func (x *GetMoneyRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetMoneyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Balance       int64                  `protobuf:"varint,1,opt,name=balance,proto3" json:"balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMoneyResponse) Reset() {
	*x = GetMoneyResponse{}
	mi := &file_newpaid_newpaid_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMoneyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMoneyResponse) ProtoMessage() {}

func (x *GetMoneyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_newpaid_newpaid_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMoneyResponse.ProtoReflect.Descriptor instead.
func (*GetMoneyResponse) Descriptor() ([]byte, []int) {
	return file_newpaid_newpaid_proto_rawDescGZIP(), []int{3}
}

func (x *GetMoneyResponse) GetBalance() int64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

var File_newpaid_newpaid_proto protoreflect.FileDescriptor

const file_newpaid_newpaid_proto_rawDesc = "" +
	"\n" +
	"\x15newpaid/newpaid.proto\x12\anewpaid\"a\n" +
	"\x0fAddMoneyRequest\x12\x1d\n" +
	"\n" +
	"grpc_token\x18\x01 \x01(\tR\tgrpcToken\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\"F\n" +
	"\x10AddMoneyResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"I\n" +
	"\x0fGetMoneyRequest\x12\x1d\n" +
	"\n" +
	"grpc_token\x18\x01 \x01(\tR\tgrpcToken\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\",\n" +
	"\x10GetMoneyResponse\x12\x18\n" +
	"\abalance\x18\x01 \x01(\x03R\abalance2\x92\x01\n" +
	"\x0eNewPaidService\x12?\n" +
	"\bAddMoney\x12\x18.newpaid.AddMoneyRequest\x1a\x19.newpaid.AddMoneyResponse\x12?\n" +
	"\bGetMoney\x12\x18.newpaid.GetMoneyRequest\x1a\x19.newpaid.GetMoneyResponseB\x89\x01\n" +
	"\vcom.newpaidB\fNewpaidProtoP\x01Z0github.com/betterde/focusly/internal/gen/newpaid\xa2\x02\x03NXX\xaa\x02\aNewpaid\xca\x02\aNewpaid\xe2\x02\x13Newpaid\\GPBMetadata\xea\x02\aNewpaidb\x06proto3"

var (
	file_newpaid_newpaid_proto_rawDescOnce sync.Once
	file_newpaid_newpaid_proto_rawDescData []byte
)

func file_newpaid_newpaid_proto_rawDescGZIP() []byte {
	file_newpaid_newpaid_proto_rawDescOnce.Do(func() {
		file_newpaid_newpaid_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_newpaid_newpaid_proto_rawDesc), len(file_newpaid_newpaid_proto_rawDesc)))
	})
	return file_newpaid_newpaid_proto_rawDescData
}

var file_newpaid_newpaid_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_newpaid_newpaid_proto_goTypes = []any{
	(*AddMoneyRequest)(nil),  // 0: newpaid.AddMoneyRequest
	(*AddMoneyResponse)(nil), // 1: newpaid.AddMoneyResponse
	(*GetMoneyRequest)(nil),  // 2: newpaid.GetMoneyRequest
	(*GetMoneyResponse)(nil), // 3: newpaid.GetMoneyResponse
}
var file_newpaid_newpaid_proto_depIdxs = []int32{
	0, // 0: newpaid.NewPaidService.AddMoney:input_type -> newpaid.AddMoneyRequest
	2, // 1: newpaid.NewPaidService.GetMoney:input_type -> newpaid.GetMoneyRequest
	1, // 2: newpaid.NewPaidService.AddMoney:output_type -> newpaid.AddMoneyResponse
	3, // 3: newpaid.NewPaidService.GetMoney:output_type -> newpaid.GetMoneyResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_newpaid_newpaid_proto_init() }
func file_newpaid_newpaid_proto_init() {
	if File_newpaid_newpaid_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_newpaid_newpaid_proto_rawDesc), len(file_newpaid_newpaid_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_newpaid_newpaid_proto_goTypes,
		DependencyIndexes: file_newpaid_newpaid_proto_depIdxs,
		MessageInfos:      file_newpaid_newpaid_proto_msgTypes,
	}.Build()
	File_newpaid_newpaid_proto = out.File
	file_newpaid_newpaid_proto_goTypes = nil
	file_newpaid_newpaid_proto_depIdxs = nil
}
