// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: events/balance_event.proto

package events

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 余额变更事件
type BalanceChangeEvent struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	UserId     int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`            // 用户ID
	ChangeType string                 `protobuf:"bytes,2,opt,name=change_type,json=changeType,proto3" json:"change_type,omitempty"` // 变更类型: "add", "deduct", "refund"
	Amount     int64                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`                          // 变更金额（分）
	Balance    int64                  `protobuf:"varint,4,opt,name=balance,proto3" json:"balance,omitempty"`                        // 变更后余额（分）
	OrderNo    string                 `protobuf:"bytes,5,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`          // 关联订单号（可选）
	Reason     string                 `protobuf:"bytes,6,opt,name=reason,proto3" json:"reason,omitempty"`                           // 变更原因（可选）
	Timestamp  int64                  `protobuf:"varint,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                    // 时间戳（Unix 时间戳，毫秒）
	// 服务标识
	SourceService string `protobuf:"bytes,8,opt,name=source_service,json=sourceService,proto3" json:"source_service,omitempty"` // 来源服务名称（谁发起的变动，如 "payment-service", "balance-center"）
	EventId       string `protobuf:"bytes,9,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`                   // 事件ID（UUID，用于去重和追踪）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BalanceChangeEvent) Reset() {
	*x = BalanceChangeEvent{}
	mi := &file_events_balance_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BalanceChangeEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BalanceChangeEvent) ProtoMessage() {}

func (x *BalanceChangeEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_balance_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BalanceChangeEvent.ProtoReflect.Descriptor instead.
func (*BalanceChangeEvent) Descriptor() ([]byte, []int) {
	return file_events_balance_event_proto_rawDescGZIP(), []int{0}
}

func (x *BalanceChangeEvent) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *BalanceChangeEvent) GetChangeType() string {
	if x != nil {
		return x.ChangeType
	}
	return ""
}

func (x *BalanceChangeEvent) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *BalanceChangeEvent) GetBalance() int64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *BalanceChangeEvent) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *BalanceChangeEvent) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *BalanceChangeEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *BalanceChangeEvent) GetSourceService() string {
	if x != nil {
		return x.SourceService
	}
	return ""
}

func (x *BalanceChangeEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

var File_events_balance_event_proto protoreflect.FileDescriptor

const file_events_balance_event_proto_rawDesc = "" +
	"\n" +
	"\x1aevents/balance_event.proto\x12\x06events\"\x93\x02\n" +
	"\x12BalanceChangeEvent\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1f\n" +
	"\vchange_type\x18\x02 \x01(\tR\n" +
	"changeType\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\x12\x18\n" +
	"\abalance\x18\x04 \x01(\x03R\abalance\x12\x19\n" +
	"\border_no\x18\x05 \x01(\tR\aorderNo\x12\x16\n" +
	"\x06reason\x18\x06 \x01(\tR\x06reason\x12\x1c\n" +
	"\ttimestamp\x18\a \x01(\x03R\ttimestamp\x12%\n" +
	"\x0esource_service\x18\b \x01(\tR\rsourceService\x12\x19\n" +
	"\bevent_id\x18\t \x01(\tR\aeventIdB\x88\x01\n" +
	"\n" +
	"com.eventsB\x11BalanceEventProtoP\x01Z/github.com/betterde/focusly/internal/gen/events\xa2\x02\x03EXX\xaa\x02\x06Events\xca\x02\x06Events\xe2\x02\x12Events\\GPBMetadata\xea\x02\x06Eventsb\x06proto3"

var (
	file_events_balance_event_proto_rawDescOnce sync.Once
	file_events_balance_event_proto_rawDescData []byte
)

func file_events_balance_event_proto_rawDescGZIP() []byte {
	file_events_balance_event_proto_rawDescOnce.Do(func() {
		file_events_balance_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_events_balance_event_proto_rawDesc), len(file_events_balance_event_proto_rawDesc)))
	})
	return file_events_balance_event_proto_rawDescData
}

var file_events_balance_event_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_events_balance_event_proto_goTypes = []any{
	(*BalanceChangeEvent)(nil), // 0: events.BalanceChangeEvent
}
var file_events_balance_event_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_events_balance_event_proto_init() }
func file_events_balance_event_proto_init() {
	if File_events_balance_event_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_events_balance_event_proto_rawDesc), len(file_events_balance_event_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_events_balance_event_proto_goTypes,
		DependencyIndexes: file_events_balance_event_proto_depIdxs,
		MessageInfos:      file_events_balance_event_proto_msgTypes,
	}.Build()
	File_events_balance_event_proto = out.File
	file_events_balance_event_proto_goTypes = nil
	file_events_balance_event_proto_depIdxs = nil
}
